services:

  mysql_backend_template_db:
    container_name: mysql_backend_template_db
    restart: always
    image: 'mysql/mysql-server:8.0'
    environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    volumes:
      - mysql_backend_template_db_local:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  js-node-web-backend-template:
    container_name: js-node-web-backend-template
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${BACKEND_PORT:-5000}:5000'
      - '${DEBUG_BACKEND_PORT:-9229}:9229'
    environment:
      - NODE_ENV=${APP_ENV}


volumes:
  mysql_backend_template_db_local:
    driver: local
