name: Run prod-branch-merge

concurrency: prod
on:
  push:
    branches:
      - main

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine last tag
        id: get_last_tag
        run: |
          echo "LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)" >> $GITHUB_ENV


      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ github.run_number }}
          LATEST_TAG: ${{ env.LATEST_TAG }}
        run: |
          gh release create "$NEW_TAG" \
            --notes-from-tag "$LATEST_TAG"

